service: service-openai

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: us-west-1
  environment:
    OPENAI_API_KEY: API

functions:
  openai:
    handler: handler.openaiFunction
    events:
      - http:
          path: /openai
          method: post



